#
#Sun Apr 19 06:16:32 EDT 2020
NonSolidLeaves.enabled=false
DayNightCycle.enabled=false
RuntimeObfuscation.enabled=true
PreventBoatBreak.enabled=true
DayNightCycle.cycleLengthMultiplier=1.0
DayNightCycle.dayToNightRatio=0.5
