# Remove Vanilla Furnace Recipes (<OUTPUT>)  OR  (<OUTPUT>, <INPUT>):
furnace.remove(<minecraft:iron_ingot>);
furnace.remove(<minecraft:gold_ingot>);
furnace.remove(<minecraft:diamond>);
furnace.remove(<minecraft:emerald>);
furnace.remove(<minecraft:redstone>);
furnace.remove(<minecraft:quartz>);
furnace.remove(<minecraft:dye:4>);
furnace.remove(<minecraft:gold_nugget>);
furnace.remove(<minecraft:coal:0>);
furnace.remove(<BigReactors:BRIngot:*>);
furnace.remove(<ThermalFoundation:material:8>);
furnace.remove(<ThermalFoundation:material:16>);
furnace.remove(<ThermalFoundation:material:64>);
furnace.remove(<ThermalFoundation:material:65>);
furnace.remove(<ThermalFoundation:material:66>);
furnace.remove(<ThermalFoundation:material:67>);
furnace.remove(<ThermalFoundation:material:68>);
furnace.remove(<ThermalFoundation:material:69>);
furnace.remove(<ThermalFoundation:material:70>);
furnace.remove(<ThermalFoundation:material:71>);
furnace.remove(<ThermalFoundation:material:72>);
furnace.remove(<ThermalFoundation:material:73>);
furnace.remove(<ThermalFoundation:material:74>);
furnace.remove(<ThermalFoundation:material:75>);
furnace.remove(<ThermalFoundation:material:96>);
furnace.remove(<ThermalFoundation:material:97>);
furnace.remove(<ThermalFoundation:material:99>);
furnace.remove(<TConstruct:materials:3>);
furnace.remove(<TConstruct:materials:4>);
furnace.remove(<TConstruct:materials:5>);
furnace.remove(<TConstruct:materials:11>);
furnace.remove(<TConstruct:materials:14>);
//furnace.remove(<TConstruct:materials:16>);		// this is having trouble... keep an eye on this
furnace.remove(<TConstruct:materials:22>);
furnace.remove(<Thaumcraft:ItemResource:3>);
furnace.remove(<Thaumcraft:ItemResource:6>);
furnace.remove(<Thaumcraft:ItemResource:14>);
furnace.remove(<libVulpes:libVulpesproductingot:*>);
furnace.remove(<libVulpes:libVulpesproductdust:*>);
furnace.remove(<advancedRocketry:advancedRocketryproductingot:*>);
furnace.remove(<DraconicEvolution:draconiumIngot>);
furnace.remove(<MineFactoryReloaded:plastic.raw>);
furnace.remove(<MineFactoryReloaded:pinkslime:1>);
furnace.remove(<MineFactoryReloaded:stone:*>);
furnace.remove(<ProjRed|Core:projectred.core.part:0>);
furnace.remove(<ProjRed|Core:projectred.core.part:10>);
furnace.remove(<ProjRed|Core:projectred.core.part:11>);
furnace.remove(<ProjRed|Core:projectred.core.part:13>);
furnace.remove(<ProjRed|Core:projectred.core.part:14>);
furnace.remove(<ProjRed|Core:projectred.core.part:55>);
furnace.remove(<ProjRed|Core:projectred.core.part:59>);
furnace.remove(<Forestry:apatite>);
furnace.remove(<rftools:dimensionalShardItem>);
furnace.remove(<Railcraft:brick.bleachedbone:2>, <Railcraft:part.bleached.clay>);
furnace.remove(<Railcraft:brick.quarried:2>, <Railcraft:cube:7>);
furnace.remove(<Railcraft:brick.abyssal:2>, <Railcraft:cube:6>);
furnace.remove(<Railcraft:brick.nether:2>, <minecraft:nether_brick>);
furnace.remove(<ExtraUtilities:block_bedrockium>);
furnace.remove(<SSTOW:sstow_materials:3>);
furnace.remove(<witchery:ingredient:18>);
furnace.remove(<FissionWarfare:quartz_chunk>);
furnace.remove(<FissionWarfare:radioactive_chunk>);
furnace.remove(<StevesCarts:ModuleComponents:12>);
furnace.remove(<TaintedMagic:ItemMaterial:0>);
furnace.remove(<TwilightForest:item.ironwoodIngot>);
furnace.remove(<TwilightForest:item.knightMetal>);


# Add Vanilla Furnace Recipes (<OUTPUT>, <INPUT>):
furnace.addRecipe(<harvestcraft:freshwaterItem>, <minecraft:potion:0>);
furnace.addRecipe(<harvestcraft:freshmilkItem>, <MineFactoryReloaded:milkbottle>);
# Add Harvestcraft Woods:
furnace.addRecipe(<minecraft:coal:1>, <harvestcraft:pamCinnamon>);
furnace.addRecipe(<minecraft:coal:1>, <harvestcraft:pamMaple>);
furnace.addRecipe(<minecraft:coal:1>, <harvestcraft:pamPaperbark>);


# Remove Thermal Expansion Furnace Recipes (<INPUT>):
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:stone>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:diamond_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:emerald_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:redstone_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:iron_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:gold_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:quartz_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:lapis_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:coal_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:gold_nugget>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:potato>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:beef>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:chicken>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:porkchop>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:nether_brick>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:soul_sand>);
mods.thermalexpansion.Furnace.removeRecipe(<minecraft:sapling:*>);
mods.thermalexpansion.Furnace.removeRecipe(<BigReactors:BRIngot:4>);
mods.thermalexpansion.Furnace.removeRecipe(<BigReactors:BRIngot:5>);
mods.thermalexpansion.Furnace.removeRecipe(<BigReactors:BRIngot:6>);
mods.thermalexpansion.Furnace.removeRecipe(<BigReactors:BRIngot:7>);
mods.thermalexpansion.Furnace.removeRecipe(<BigReactors:BRIngot:9>);
mods.thermalexpansion.Furnace.removeRecipe(<BigReactors:YelloriteOre:*>);
mods.thermalexpansion.Furnace.removeRecipe(<denseores:block0:*>);
mods.thermalexpansion.Furnace.removeRecipe(<denseores:block1:*>);
mods.thermalexpansion.Furnace.removeRecipe(<MineFactoryReloaded:stone:*>);
mods.thermalexpansion.Furnace.removeRecipe(<MineFactoryReloaded:plastic.sheet>);
mods.thermalexpansion.Furnace.removeRecipe(<MineFactoryReloaded:straw>);
mods.thermalexpansion.Furnace.removeRecipe(<MineFactoryReloaded:ruler>);
mods.thermalexpansion.Furnace.removeRecipe(<MineFactoryReloaded:plastic.bag>);
mods.thermalexpansion.Furnace.removeRecipe(<MineFactoryReloaded:plastic:*>);
mods.thermalexpansion.Furnace.removeRecipe(<MineFactoryReloaded:rubber.bar>);
mods.thermalexpansion.Furnace.removeRecipe(<MineFactoryReloaded:brick:13>);
mods.thermalexpansion.Furnace.removeRecipe(<MineFactoryReloaded:pinkslime.block>);
mods.thermalexpansion.Furnace.removeRecipe(<Thaumcraft:blockCustomOre:0>);
mods.thermalexpansion.Furnace.removeRecipe(<Thaumcraft:ItemNugget:16>);
mods.thermalexpansion.Furnace.removeRecipe(<Thaumcraft:ItemNugget:17>);
mods.thermalexpansion.Furnace.removeRecipe(<Thaumcraft:ItemNugget:18>);
mods.thermalexpansion.Furnace.removeRecipe(<Thaumcraft:ItemNugget:19>);
mods.thermalexpansion.Furnace.removeRecipe(<Thaumcraft:ItemNugget:20>);
mods.thermalexpansion.Furnace.removeRecipe(<Thaumcraft:ItemNugget:21>);
mods.thermalexpansion.Furnace.removeRecipe(<Thaumcraft:ItemNugget:31>);
mods.thermalexpansion.Furnace.removeRecipe(<Thaumcraft:ItemShard:6>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalExpansion:material:514>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:Ore:*>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:0>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:1>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:32>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:33>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:34>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:35>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:36>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:37>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:38>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:39>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:40>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:41>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:42>);
mods.thermalexpansion.Furnace.removeRecipe(<ThermalFoundation:material:43>);
mods.thermalexpansion.Furnace.removeRecipe(<TConstruct:materials:38>);
mods.thermalexpansion.Furnace.removeRecipe(<TConstruct:materials:39>);
mods.thermalexpansion.Furnace.removeRecipe(<TConstruct:materials:40>);
mods.thermalexpansion.Furnace.removeRecipe(<TConstruct:materials:41>);
mods.thermalexpansion.Furnace.removeRecipe(<TConstruct:materials:42>);
mods.thermalexpansion.Furnace.removeRecipe(<TConstruct:oreBerries:*>);
mods.thermalexpansion.Furnace.removeRecipe(<TConstruct:SearedBrick:5>);
mods.thermalexpansion.Furnace.removeRecipe(<Railcraft:ore:*>);
mods.thermalexpansion.Furnace.removeRecipe(<Railcraft:part.bleached.clay>);
mods.thermalexpansion.Furnace.removeRecipe(<Railcraft:cube:*>);
mods.thermalexpansion.Furnace.removeRecipe(<Railcraft:brick.nether:*>);
mods.thermalexpansion.Furnace.removeRecipe(<DraconicEvolution:draconiumDust>);
mods.thermalexpansion.Furnace.removeRecipe(<DraconicEvolution:draconiumBlend>);
mods.thermalexpansion.Furnace.removeRecipe(<rftools:dimensionalShardBlock>);
mods.thermalexpansion.Furnace.removeRecipe(<Forestry:resources:0>);
mods.thermalexpansion.Furnace.removeRecipe(<libVulpes:libVulpesore0:*>);
mods.thermalexpansion.Furnace.removeRecipe(<libVulpes:libVulpesproductdust:*>);
mods.thermalexpansion.Furnace.removeRecipe(<witchery:ingredient:102>);
mods.thermalexpansion.Furnace.removeRecipe(<ore:oreAmber>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedAluminium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedDraconium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedSilver>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedTin>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedGold>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedIron>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedCobalt>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedArdite>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedNickel>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedTitanium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedYellorium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedPlatinum>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedIridium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedCopper>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedLead>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedKnightmetal>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedShadow>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:crushedIronwood>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterYellorium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterTitanium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterDraconium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterIridium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterPlatinum>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterArdite>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterCobalt>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterNickel>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterAluminium>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterShadow>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterIronwood>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:clusterKnightmetal>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:dustShadow>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:dustIronwood>);
mods.thermalexpansion.Furnace.removeRecipe(<aobd:dustKnightmetal>);
mods.thermalexpansion.Furnace.removeRecipe(<advancedRocketry:advancedRocketryproductdust:*>);
mods.thermalexpansion.Furnace.removeRecipe(<ProjRed|Core:projectred.core.part:40>);
mods.thermalexpansion.Furnace.removeRecipe(<ProjRed|Core:projectred.core.part:41>);
mods.thermalexpansion.Furnace.removeRecipe(<ProjRed|Core:projectred.core.part:42>);
mods.thermalexpansion.Furnace.removeRecipe(<ProjRed|Core:projectred.core.part:43>);
mods.thermalexpansion.Furnace.removeRecipe(<ProjRed|Core:projectred.core.part:57>);
mods.thermalexpansion.Furnace.removeRecipe(<ProjRed|Core:projectred.core.part:58>);
mods.thermalexpansion.Furnace.removeRecipe(<ExtraUtilities:cobblestone_compressed:*>);
mods.thermalexpansion.Furnace.removeRecipe(<FissionWarfare:uranium_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<FissionWarfare:sulfur_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<FissionWarfare:quartz_ore>);
mods.thermalexpansion.Furnace.removeRecipe(<StevesCarts:ModuleComponents:11>);
mods.thermalexpansion.Furnace.removeRecipe(<TaintedMagic:BlockShadowOre>);
mods.thermalexpansion.Furnace.removeRecipe(<TwilightForest:item.ironwoodRaw>);
mods.thermalexpansion.Furnace.removeRecipe(<TwilightForest:item.shardCluster>);

# Add Thermal Expansion Furnace Recipes (InputRF, <Input>, <Output>):
mods.thermalexpansion.Furnace.addRecipe(250, <minecraft:potion:0>, <harvestcraft:freshwaterItem>);
mods.thermalexpansion.Furnace.addRecipe(250, <MineFactoryReloaded:milkbottle>, <harvestcraft:freshmilkItem>);
# Fix RockWool Recipe:
mods.thermalexpansion.Furnace.addRecipe(800, <ThermalExpansion:material:514>, <ThermalExpansion:Rockwool:8>);
# Fix Food Recipes:
mods.thermalexpansion.Furnace.addRecipe(800, <minecraft:potato>, <minecraft:baked_potato>);
mods.thermalexpansion.Furnace.addRecipe(800, <minecraft:beef>, <minecraft:cooked_beef>);
mods.thermalexpansion.Furnace.addRecipe(800, <minecraft:chicken>, <minecraft:cooked_chicken>);
mods.thermalexpansion.Furnace.addRecipe(800, <minecraft:porkchop>, <minecraft:cooked_porkchop>);
# Harvestcraft Woods:
mods.thermalexpansion.Furnace.addRecipe(800, <harvestcraft:pamCinnamon>, <minecraft:coal:1>);
mods.thermalexpansion.Furnace.addRecipe(800, <harvestcraft:pamMaple>, <minecraft:coal:1>);
mods.thermalexpansion.Furnace.addRecipe(800, <harvestcraft:pamPaperbark>, <minecraft:coal:1>);
# Nether from NetherCobble:
mods.thermalexpansion.Furnace.addRecipe(800, <Railcraft:brick.nether:5>, <Railcraft:brick.nether:2>);

# Remove Furnace Fuels
furnace.setFuel(<harvestcraft:fishtrap>, 0);
furnace.setFuel(<harvestcraft:animaltrap>, 0);
furnace.setFuel(<TConstruct:CraftingSlab:5>, 0);
furnace.setFuel(<TConstruct:ToolStationBlock:*>, 0);
furnace.setFuel(<ExtraTrees:door:*>, 0);
furnace.setFuel(<ExtraTrees:stairs:*>, 0);
furnace.setFuel(<ExtraTrees:carpentry:*>, 0);
furnace.setFuel(<imc:item_machete_wood>, 0);
furnace.setFuel(<witchery:huntsmanspear>, 0);
furnace.setFuel(<witchery:brew.fuel>, 0);
